== 认证服务

=== 功能

. 支持RBAC的认证服务
. 支持菜单级和资源级（action）的授权
. 支持JDBC或Mongo的持久化
. 支持自助注册及密码找回

=== 5分钟上手

. 添加依赖

 <dependency>
   <groupId>com.ecfront</groupId>
   <artifactId>ezf-auth</artifactId>
   <version>3.0.0-SNAPSHOT</version>
 <dependency>

. 添加配置

 "auth": {},
 "storage.mongo": {
   "host": "<服务IP>",
   "port": 27017,
   "db_name": "test"
 },
 "rpc.http": {
   "host": "0.0.0.0",
   "port": 8080
 },
 "distributed":{},
 "redis": {
   "host": "<服务IP>",
   "port": 6379
 }
 
. 启动服务

 EZManager.start()
 
. 登录

 POST http://127.0.0.1:8080/public/auth/login/" body: {"id":"admin","password":"admin"}
 返回登录信息

=== 依赖

服务依赖：rpc.http、redis、distributed、storage.mongo或storage.jdbc、mail（可选，允许注册或开放找回密码功能时必选）

环境依赖：redis、mongo或mysql

=== 配置

[source,json]
----
"auth": {
  "allowRegister": false, <1>
  "customLogin": false,  <2>
  "selfActive": true, <3>
  "defaultRoleFlag": "user", <4>
  "defaultOrganizationCode": "", <5>
  "publicUriPrefix": "/public/", <6>
  "loginUrl": "#/auth/login", <7>
  "loginKeepSeconds": 0, <8>
  "activeKeepSeconds": 86400, <9>
  "extAccountStorage": "", <10>
  "useRelTable": false, <11>
  "customTables": {  <12>
    "organization": "",  <13>
    "account": "",  <14>
    "resource": "",  <15>
    "role": "",  <16>
    "menu": "",  <17>
    "rel_account_role": "",  <18>
    "rel_role_resource": "",  <19>
    "rel_menu_role": ""  <20>
  },
  "storage":"mongo", <21>
  "loginLimit": { <22>
    "showCaptcha":2147483647 <23>
  },
}
----
<1> 是否允许注册，注册后账户处于禁用状态，需要激活
<2> 是否启用自定义登录，如果为true的话默认登录URL会被禁用
<3> 是否允许自助激活，true：会发送激活邮件自助激活，false：需要管理员手工激活
<4> 默认角色标识，注册时账户默认的角色
<5> 默认组织编码，注册时账户默认的组织
<6> 公开URI的前缀，以此前缀开头的URI不需要认证
<7> 登录URL，注册或找回密码激活成功后会跳转到登录URL，如果此配置值不带http前缀则使用`rpc-http`中`webUrl`做为基础路径
<8> 登录保持时间，单位秒，指定登录会话多少秒后过期，0表示不过期
<9> 注册或找回密码激活有效期，单位秒
<10> 扩展账号持久化类路径，可选，默认对于扩展的账号信息存储在`ez_account`表中的`ext_info`字段中，如果需要将扩展信息存储在独立表中时可以定义一个继承自`BaseModel`的实体及对应的持久化实现，然后指定其类路径
<11> 是否使用关联表（多对多关联中间表），多用于JDBC持久化，建议在原生不支持json的关系型数据启用此项
<12> 是否使用自定义表名
<13> 自定义组织表名
<14> 自定义账户表名
<15> 自定义资源表名
<16> 自定义角色表名
<17> 自定义菜单表名
<18> 自定义账户角色关联表名
<19> 自定义角色资源关联表名
<20> 自定义菜单角色关联表名
<21> 持久化实现，支持`mongo`或`jdbc`
<22> 登录限制
<23> 在连续多次登录失败后显示验证码

NOTE: `storage:jdbc & useRelTable不存在或等于false`时请执行`ez_ddl.sql`以创建基础表，`storage:jdbc & useRelTable=true`时请执行`ez_ddl_with_rel.sql`以创建带关联表的基础表

=== 认证服务接入

在原有HTTP服务方法中修改 `EZRPCContext` 为 `EZAuthContext` 即可，如

[source,scala]
----
@POST("")
def testAuth(parameter: Map[String, String], body: Account_VO, context: EZAuthContext): Resp[Void]
----

EZAuthContext在EZRPCContext基础上添加了两个字段：

. token 认证的Token值
. loginInfo 登录信息

=== 事件

==== 初始化新组织事件

[source,scala]
----
ServiceAdapter.ezEvent_organizationInit.<subscribe | subscribeOneNode>({
  orgCode:String =>
    // your code
})
----

==== 登录成功事件

[source,scala]
----
ServiceAdapter.ezEvent_loginSuccess.<subscribe | subscribeOneNode>({
  tokenInfo:Token_Info_VO =>
    // your code
})
----

==== 注销事件

[source,scala]
----
ServiceAdapter.ezEvent_logout.<subscribe | subscribeOneNode>({
  tokenInfo:Token_Info_VO =>
    // your code
})
----

=== 预定义认证接口调用

==== 说明

. 无特殊说明的情况下所有请求的header Content-Type为application/json
. 无特殊说明的情况下所有返回值均为Json，由以下格式构成：

 {
   "code":"<状态码，200表示成功，其它表示失败>",
   "message":"<消息，多在出现失败时显示失败原因>",
   "body":"<返回主体内容，不同接口内容不同>"
 }

. 如果是分页查询，则返回格式构成如下：

 {
   "code":"<状态码，200表示成功，其它表示失败>",
   "message":"<消息，多在出现失败时显示失败原因>",
   "body": {
       "pageNumber": <当前页，从1开始>,
       "pageSize": <每页条数>,
       "pageTotal": <总页数>,
       "recordTotal": <总记录数>,
       "objects": [ 返回主体内容，不同接口内容不同 ]
   }
 }

==== 登录

*请求*

----
POST /public/auth/login/
----

body:
[source,text]
{
  "id":String, // 登录Id或email
  "password":String, // 密码
  "organizationCode":String, // 所属组织,不传时使用配置中的`defaultOrganizationCode`
  "captcha":String // 验证码
}

*响应内容主体*

[source,text]
{
  "token": String, // token，前端需要保存此值，用于后续获取登录信息
  "login_id": String, // 登录id
  "name": String, // 姓名
  "email": String, // email
  "image": String, // 头像URL
  "organization_code": String, // 组织编码
  "role_codes": List[String], // 角色编码列表
  "ext_id": String, // 扩展Id
  "ext_info": Map[String, Any] // 扩展信息
}

NOTE: `ext_id`只在使用`extAccountStorage`时有意义

==== 获取验证码

*请求*

----
GET /public/auth/captcha/<所属组织编码>/<登录Id或email>/
----

*响应内容主体*

__验证码图片__

==== 注销

*请求*

----
GET /auth/logout/?__ez_token__=<token>
----

*响应内容主体*

null

==== 获取登录信息

*请求*

----
GET /auth/logininfo/?__ez_token__=<token>
----

*响应内容主体*

同`登录`的响应内容主体

==== 获取菜单（带权限过滤）

*请求*

----
GET /public/menu/?__ez_token__=<token>  `__ez_token__`可选，不加时显示公共（不需要认证）的菜单
----

*响应内容主体*

[source,json]
[
  {
    "code": String, // 菜单编码
    "uri": String, // 菜单点击的URI
    "name": String, // 菜单名称
    "icon": String, // 菜单图标名称
    "translate": String, // 菜单翻译（i18n用）
    "role_codes": List[String], // 所属角色编码列表
    "parent_code": String, // 父菜单编码，用于多级菜单
    "sort": Int, // 排序，倒序
    "organization_code": String // 所属组织编码
  },
  ...
]

==== 注册

*请求*

----
POST /public/register/
----

body

[source,text]
{
  "login_id": String,  // 登录id
  "name": String, // 姓名
  "image": String, // 头像
  "email": String, // Email
  "new_password": String // 密码
}

*响应内容主体*

null，允许自助激活时会发送激活邮件

==== 激活账号

*请求*

----
GET /public/active/account/<加密字符串>/ 来自邮件中的链接
----

*响应内容主体*

跳转到登录URL 或 返回错误信息

==== 找回（重置）密码

*请求*

----
PUT /public/findpassword/<email>/
----

body
[source,text]
{
  "new_password": String  // 新的密码
}

*响应内容主体*

null，发送激活邮件

==== 激活新密码

*请求*

----
GET /public/active/password/<加密字符串>/ 来自邮件中的链接
----

*响应内容主体*

跳转到登录URL 或 返回错误信息

==== 获取登录账号信息

* 此操作直接从数据中获取数据，上文`获取账号信息`从缓存中获取

*请求*

----
GET /auth/manage/account/bylogin/?__ez_token__=<token>
----

*响应内容主体*

[source,text]
{
  "id": String,  // 数据库id
  "login_id": String,  // 登录id
  "name": String, // 姓名
  "image": String, // 头像
  "email": String, // Email
  "ext_id": String, // 扩展id
  "ext_info": Map[String, Any] // 扩展信息
}

==== 更新登录账号信息

*请求*

----
PUT /auth/manage/account/bylogin/?__ez_token__=<token>
----

body
[source,text]
{
  "name": String, // 姓名
  "image": String, // 头像
  "email": String, // Email
  "current_password": String, // 当前密码
  "new_password": String // 新密码，如果要修改密码此字段必填
}

IMPORTANT: `current_password`必须填写正确，否则无法修改

*响应内容主体*

null

==== （管理接口）添加资源

*请求*

----
POST /auth/manage/resource/?__ez_token__=<token>
----

body
[source,text]
{
  "method": String,  // Http方法，大写
  "uri": String,  // 资源URI
  "name": String // 资源名称
}

*响应内容主体*

[source,text]
{
  "id": String,  // 数据库id
  "code": String,  // 资源编码
  "method": String,  // Http方法，大写
  "uri": String,  // 资源uri
  "name": String, // 资源名称
  "enable": Boolean, // 是否启用
  "create_user": String, // 创建用户login_id
  "create_org": String, // 创建组织编码
  "create_time": Long, // 创建时间（yyyyMMddHHmmssSSS）
  "update_user": String, // 更新用户login_id
  "update_org": String, // 更新组织编码
  "update_time": Long // 更新时间（yyyyMMddHHmmssSSS）
}

==== （管理接口）更新资源

*请求*

----
PUT /auth/manage/resource/<资源id>/?__ez_token__=<token>
----

body
[source,text]
{
  "name": String // 资源名称
}

NOTE: 只能修改`name`

*响应内容主体*

同`（管理接口）添加资源`的响应内容主体

==== （管理接口）查找资源列表

*请求*

----
GET /auth/manage/resource/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
[
  {
   同`（管理接口）添加资源`的响应内容主体
  },
  ...
]

==== （管理接口）查找启用资源列表

*请求*

----
GET /auth/manage/resource/enable/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

同`（管理接口）查找启用资源列表`的响应内容主体

==== （管理接口）分页查找资源列表

*请求*

----
GET /auth/manage/resource/page/<当前页，从1开始>/<每页显示条数>/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
{
  "pageNumber":Long, // 当前页，从1开始
  "pageSize":Int, // 每页显示条数
  "pageTotal":Long, // 总共页数
  "recordTotal":Long, // 总共记录数
  // 当前页的实体列表
  "objects":[
    {
     同`（管理接口）添加资源`的响应内容主体
    },
    ...
  ]
}

==== （管理接口）获取一个资源

*请求*

----
GET /auth/manage/resource/<资源id>/?__ez_token__=<token>
----

*响应内容主体*

同`（管理接口）添加资源`的响应内容主体

==== （管理接口）删除一个资源

*请求*

----
DELETE /auth/manage/resource/<资源id>/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）启用一个资源

*请求*

----
GET /auth/manage/resource/<资源id>/enable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）禁用一个资源

*请求*

----
GET /auth/manage/resource/<资源id>/disable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）导出资源列表

*请求*

----
GET /auth/manage/resource/export/?__ez_token__=<token>
----

*响应内容主体*

资源中可导出字段的列表，格式为逗号分割符

==== （管理接口）添加组织

*请求*

----
POST /auth/manage/organization/?__ez_token__=<token>
----

body
[source,text]
{
  "code": String,  // 编码编码
  "name": String, // 组织名称
  "image": String // 组织图标
}

*响应内容主体*

[source,text]
{
  "id": String,  // 数据库id
  "code": String,  // 编码编码
  "name": String, // 组织名称
  "image": String, // 组织图标
  "enable": Boolean, // 是否启用
  "create_user": String, // 创建用户login_id
  "create_org": String, // 创建组织编码
  "create_time": Long, // 创建时间（yyyyMMddHHmmssSSS）
  "update_user": String, // 更新用户login_id
  "update_org": String, // 更新组织编码
  "update_time": Long // 更新时间（yyyyMMddHHmmssSSS）
}

==== （管理接口）更新组织

*请求*

----
PUT /auth/manage/organization/<组织id>/?__ez_token__=<token>
----

body
[source,text]
{
  "name": String, // 组织名称
  "image": String // 组织图标
}

NOTE: 只能修改`name`和`image`

*响应内容主体*

同`（管理接口）添加组织`的响应内容主体

==== （管理接口）查找组织列表

*请求*

----
GET /auth/manage/organization/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
[
  {
   同`（管理接口）添加组织`的响应内容主体
  },
  ...
]

==== （管理接口）查找启用组织列表

*请求*

----
GET /auth/manage/organization/enable/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

同`（管理接口）查找启用组织列表`的响应内容主体

==== （管理接口）分页查找组织列表

*请求*

----
GET /auth/manage/organization/page/<当前页，从1开始>/<每页显示条数>/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
{
  "pageNumber":Long, // 当前页，从1开始
  "pageSize":Int, // 每页显示条数
  "pageTotal":Long, // 总共页数
  "recordTotal":Long, // 总共记录数
  // 当前页的实体列表
  "objects":[
    {
     同`（管理接口）添加组织`的响应内容主体
    },
    ...
  ]
}

==== （管理接口）获取一个组织

*请求*

----
GET /auth/manage/organization/<组织id>/?__ez_token__=<token>
----

*响应内容主体*

同`（管理接口）添加组织`的响应内容主体

==== （管理接口）删除一个组织

*请求*

----
DELETE /auth/manage/organization/<组织id>/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）启用一个组织

*请求*

----
GET /auth/manage/organization/<组织id>/enable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）禁用一个组织

*请求*

----
GET /auth/manage/organization/<组织id>/disable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）导出组织列表

*请求*

----
GET /auth/manage/organization/export/?__ez_token__=<token>
----

*响应内容主体*

组织中可导出字段的列表，格式为逗号分割符

==== （管理接口）上传组织图标

*请求*

----
POST /auth/manage/organization/res/?__ez_token__=<token>
----

body 上传的图标

*响应内容主体*

上传图标的uri

==== （管理接口）获取组织图标

*请求*

----
GET <`（管理接口）上传组织图标`中返回的uri>?__ez_token__=<token>
----

*响应内容主体*

显示上传的图标

==== （管理接口）添加角色

*请求*

----
POST /auth/manage/role/?__ez_token__=<token>
----

body
[source,text]
{
  "flag": String,  // 角色标识
  "name": String, // 角色名称
  "resource_codes": List[String], // 所属资源编码列表
  "organization_code": String // 所属组织编码
}

*响应内容主体*

[source,text]
{
  "id": String,  // 数据库id
  "code": String,  // 编码编码
  "flag": String,  // 角色标识
  "name": String, // 角色名称
  "resource_codes": List[String], // 所属资源编码列表
  "organization_code": String, // 所属组织编码
  "enable": Boolean, // 是否启用
  "create_user": String, // 创建用户login_id
  "create_org": String, // 创建角色编码
  "create_time": Long, // 创建时间（yyyyMMddHHmmssSSS）
  "update_user": String, // 更新用户login_id
  "update_org": String, // 更新角色编码
  "update_time": Long // 更新时间（yyyyMMddHHmmssSSS）
}

==== （管理接口）更新角色

*请求*

----
PUT /auth/manage/role/<角色id>/?__ez_token__=<token>
----

body
[source,text]
{
  "name": String, // 角色名称
  "resource_codes": List[String], // 所属资源编码列表
}

NOTE: 只能修改`name`和`resource_codes`


*响应内容主体*

同`（管理接口）添加角色`的响应内容主体

==== （管理接口）查找角色列表

*请求*

----
GET /auth/manage/role/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
[
  {
   同`（管理接口）添加角色`的响应内容主体
  },
  ...
]

==== （管理接口）查找启用角色列表

*请求*

----
GET /auth/manage/role/enable/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

同`（管理接口）查找启用角色列表`的响应内容主体

==== （管理接口）分页查找角色列表

*请求*

----
GET /auth/manage/role/page/<当前页，从1开始>/<每页显示条数>/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
{
  "pageNumber":Long, // 当前页，从1开始
  "pageSize":Int, // 每页显示条数
  "pageTotal":Long, // 总共页数
  "recordTotal":Long, // 总共记录数
  // 当前页的实体列表
  "objects":[
    {
     同`（管理接口）添加角色`的响应内容主体
    },
    ...
  ]
}

==== （管理接口）获取一个角色

*请求*

----
GET /auth/manage/role/<角色id>/?__ez_token__=<token>
----

*响应内容主体*

同`（管理接口）添加角色`的响应内容主体

==== （管理接口）删除一个角色

*请求*

----
DELETE /auth/manage/role/<角色id>/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）启用一个角色

*请求*

----
GET /auth/manage/role/<角色id>/enable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）禁用一个角色

*请求*

----
GET /auth/manage/role/<角色id>/disable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）导出角色列表

*请求*

----
GET /auth/manage/role/export/?__ez_token__=<token>
----

*响应内容主体*

角色中可导出字段的列表，格式为逗号分割符

==== （管理接口）添加账户

*请求*

----
POST /auth/manage/account/?__ez_token__=<token>
----

body
[source,text]
{
  "login_id": String, // 登录id
  "name": String, // 姓名
  "email": String, // email
  "image": String, // 头像URL
  "password": String, // 密码
  "role_codes": List[String], // 角色编码列表
  "organization_code": String, // 所属组织编码
  "ext_id": String, // 扩展Id
  "ext_info": Map[String, Any] // 扩展信息
}

*响应内容主体*

[source,text]
{
  "id": String,  // 数据库id
  "code": String,  // 账户编码
  "login_id": String, // 登录id
  "name": String, // 姓名
  "email": String, // email
  "image": String, // 头像URL
  "password": String, // 密码
  "role_codes": List[String], // 角色编码列表
  "organization_code": String, // 所属组织编码
  "oauth": Map[String, String], // oauth信息
  "ext_id": String, // 扩展Id
  "ext_info": Map[String, Any] // 扩展信息
  "enable": Boolean, // 是否启用
  "create_user": String, // 创建用户login_id
  "create_org": String, // 创建账户编码
  "create_time": Long, // 创建时间（yyyyMMddHHmmssSSS）
  "update_user": String, // 更新用户login_id
  "update_org": String, // 更新账户编码
  "update_time": Long // 更新时间（yyyyMMddHHmmssSSS）
}

==== （管理接口）更新账户

*请求*

----
PUT /auth/manage/account/<账户id>/?__ez_token__=<token>
----

body
[source,text]
{
  "name": String, // 姓名
  "email": String, // email
  "image": String, // 头像URL
  "password": String, // 密码
  "role_codes": List[String], // 角色编码列表
  "ext_info": Map[String, Any] // 扩展信息
}

NOTE: 只能修改`name`、`email`、`image`、`password`、`role_codes`和`ext_info`

*响应内容主体*

同`（管理接口）添加账户`的响应内容主体

==== （管理接口）查找账户列表

*请求*

----
GET /auth/manage/account/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
[
  {
   同`（管理接口）添加账户`的响应内容主体
  },
  ...
]

==== （管理接口）查找启用账户列表

*请求*

----
GET /auth/manage/account/enable/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

同`（管理接口）查找启用账户列表`的响应内容主体

==== （管理接口）分页查找账户列表

*请求*

----
GET /auth/manage/account/page/<当前页，从1开始>/<每页显示条数>/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
{
  "pageNumber":Long, // 当前页，从1开始
  "pageSize":Int, // 每页显示条数
  "pageTotal":Long, // 总共页数
  "recordTotal":Long, // 总共记录数
  // 当前页的实体列表
  "objects":[
    {
     同`（管理接口）添加账户`的响应内容主体
    },
    ...
  ]
}

==== （管理接口）获取一个账户

*请求*

----
GET /auth/manage/account/<账户id>/?__ez_token__=<token>
----

*响应内容主体*

同`（管理接口）添加账户`的响应内容主体

==== （管理接口）删除一个账户

*请求*

----
DELETE /auth/manage/account/<账户id>/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）启用一个账户

*请求*

----
GET /auth/manage/account/<账户id>/enable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）禁用一个账户

*请求*

----
GET /auth/manage/account/<账户id>/disable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）导出账户列表

*请求*

----
GET /auth/manage/account/export/?__ez_token__=<token>
----

*响应内容主体*

账户中可导出字段的列表，格式为逗号分割符

==== （管理接口）上传账户头像

*请求*

----
POST /auth/manage/role/res/?__ez_token__=<token>
----

body 上传的头像

*响应内容主体*

上传头像的uri

==== （管理接口）获取账户头像

*请求*

----
GET <`（管理接口）上传账户头像`中返回的uri>?__ez_token__=<token>
----

*响应内容主体*

显示上传的头像

==== （管理接口）添加菜单

*请求*

----
POST /auth/manage/menu/?__ez_token__=<token>
----

body
[source,text]
{
  "uri": String, // 菜单点击的URI
  "name": String, // 菜单名称
  "icon": String, // 菜单图标名称
  "translate": String, // 菜单翻译（i18n用）
  "role_codes": List[String], // 所属角色编码列表
  "parent_code": String, // 父菜单编码，用于多级菜单
  "sort": Int, // 排序，倒序
  "organization_code": String // 所属组织编码
}

*响应内容主体*

[source,text]
{
  "id": String,  // 数据库id
  "code": String,  // 菜单编码
  "uri": String, // 菜单点击的URI
  "name": String, // 菜单名称
  "icon": String, // 菜单图标名称
  "translate": String, // 菜单翻译（i18n用）
  "role_codes": List[String], // 所属角色编码列表
  "parent_code": String, // 父菜单编码，用于多级菜单
  "sort": Int, // 排序，倒序
  "organization_code": String, // 所属组织编码
  "enable": Boolean, // 是否启用
  "create_user": String, // 创建用户login_id
  "create_org": String, // 创建菜单编码
  "create_time": Long, // 创建时间（yyyyMMddHHmmssSSS）
  "update_user": String, // 更新用户login_id
  "update_org": String, // 更新菜单编码
  "update_time": Long // 更新时间（yyyyMMddHHmmssSSS）
}

==== （管理接口）更新菜单

*请求*

----
PUT /auth/manage/menu/<菜单id>/?__ez_token__=<token>
----

body
[source,text]
{
  "name": String, // 菜单名称
  "icon": String, // 菜单图标名称
  "translate": String, // 菜单翻译（i18n用）
  "role_codes": List[String], // 所属角色编码列表
  "parent_code": String, // 父菜单编码，用于多级菜单
  "sort": Int // 排序，倒序
}

NOTE: 只能修改`name`、`icon`、`translate`、`parent_code`、`role_codes`和`sort`

*响应内容主体*

同`（管理接口）添加菜单`的响应内容主体

==== （管理接口）查找菜单列表

*请求*

----
GET /auth/manage/menu/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
[
  {
   同`（管理接口）添加菜单`的响应内容主体
  },
  ...
]

==== （管理接口）查找启用菜单列表

*请求*

----
GET /auth/manage/menu/enable/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

同`（管理接口）查找启用菜单列表`的响应内容主体

==== （管理接口）分页查找菜单列表

*请求*

----
GET /auth/manage/menu/page/<当前页，从1开始>/<每页显示条数>/?__ez_token__=<token>&condition=<查找条件，sql或mongo json>  condition可选
----

*响应内容主体*

[source,text]
{
  "pageNumber":Long, // 当前页，从1开始
  "pageSize":Int, // 每页显示条数
  "pageTotal":Long, // 总共页数
  "recordTotal":Long, // 总共记录数
  // 当前页的实体列表
  "objects":[
    {
     同`（管理接口）添加菜单`的响应内容主体
    },
    ...
  ]
}

==== （管理接口）获取一个菜单

*请求*

----
GET /auth/manage/menu/<菜单id>/?__ez_token__=<token>
----

*响应内容主体*

同`（管理接口）添加菜单`的响应内容主体

==== （管理接口）删除一个菜单

*请求*

----
DELETE /auth/manage/menu/<菜单id>/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）启用一个菜单

*请求*

----
GET /auth/manage/menu/<菜单id>/enable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）禁用一个菜单

*请求*

----
GET /auth/manage/menu/<菜单id>/disable/?__ez_token__=<token>
----

*响应内容主体*

null

==== （管理接口）导出菜单列表

*请求*

----
GET /auth/manage/menu/export/?__ez_token__=<token>
----

*响应内容主体*

菜单中可导出字段的列表，格式为逗号分割符
