== RPC服务

=== 功能

. 支持HTTP和WebSocket服务
. 基于注解服务发现
. Restful风格，支持GET POST PUT DELETE等常用方法
. 支持HTTPS
. 支持Json跨域请求
. 支持拦截器栈，可适配权限认证等服务
. 提供同步及异步HTTP客户端
. 提供CRUD脚手架服务

=== 5分钟上手

. 添加依赖

 <dependency>
   <groupId>com.ecfront</groupId>
   <artifactId>ezf-rpc-<http或websocket></artifactId>
   <version>3.0.0-SNAPSHOT</version>
 <dependency>

. 添加配置

 // HTTP
 "rpc.http": {
   "servicePath": "com.foo.api"
 }
 
 // 或 WebSocket
 "rpc.websocket": {
   "servicePath": "com.foo.api"
 }

. 在`com.foo.api`包下添加scala类

 @RPC("/test/")
 @HTTP 或 @WebSocket
 object TestService {
    @POST("") 或 @REQUEST("")
    def getTest(parameter: Map[String, String],body:String, context: EZRPCContext): Resp[String] = {
      Resp.success(String)
    }
 }

. 启动服务

 EZManager.start()
 
. 访问

 // HTTP
 POST http://127.0.0.1/test/" body: "Hello World"
 返回 "Hello World"
 
 // 或 WebSocket
 写个HTML页面
 <html>
 <head></head>
 <script>
     var socket_resource;
     if (window.WebSocket) {
         socket= new WebSocket("ws://localhost/test/");
         socket.onmessage = function (event) {
             console.log("received : " + JSON.parse(event.data));
         };
         socket.onopen = function (event) {
             console.log("opened!");
         };
         socket.onclose = function (event) {
             console.log("closed.");
         };
     } else {
         alert("Your browser does not support Websockets. (Use Chrome)");
     }
     function send() {
         socket.send(JSON.stringify({
             f1: "1111"
         }));
     }
 </script>
 <body>
 <input id="btnSend" type="button" value="POST" onclick="send()"/>
 </body>
 </html>
 打开测试，OK

=== 依赖

服务依赖：storage.mongo或storage.jdbc（可选，使用CRUD脚手架服务时必选）

=== HTTP配置

----
"rpc.http": {
  "servicePath": "", <1>
  "host": "127.0.0.1", <2>
  "port": 80/443, <3>
  "publicUrl": "", <4>
  "webUrl": "", <5>
  "resourcePath": "/tmp/", <6>
  "accessControlAllowOrigin": "*", <7>
  "ssl": { <8>
    "keyPath": "", <9>
    "keyPassword": "" <10>
  },
  monitor": { <11>
    "slow": {<12>
      "time": 10000, <13>
      "includes": [], <14>
      "excludes": [] <15>
    }
  }
}
----
<1> HTTP服务发现的根包，系统会以此包为基础，扫描子孙路径下所有带@RPC及@HTTP的类，并将其类中带@GET @POST @PUT @DELETE注解的方法加入到路由表中
<2> IP或主机名
<3> 端口号，HTTP默认80，HTTPS默认443
<4> 对外开放的URL，默认是 `http(s)://host:port/`，服务需要对外发布、代理转发等场景下可以配置此项向外暴露服务，在用户注册激活及找回密码等功能时会发送以此URL开头的链接
<5> Web页面的URL，默认同`publicUrl`，此配置用于用户注册激活及找回密码等功能时跳转到登录页面时做为登录登录URL的前缀路径
<6> 资源目录，上传文件的基础目录
<7> 跨域请求允许的来源域，*表示允许所有域
<8> SSL配置
<9> SSL证书路径，可以是绝对路径，也可以是相对路径
<10> SSL证书密码
<11> 是否使用请求监控
<12> 是否使用慢请求监控
<13> 慢请求时间定义，请求大于此时间会记录到日志，单位毫秒
<14> 包含的请求URI，如果此字段存在，那么只会记录此URI中的请求
<15> 排除的请求URI，如果此字段存在，那么在此URI中的请求都不会记录

IMPORTANT: 资源目录(resourcePath），需要禁用此目录及子孙目录的执行权限

NOTE: SSL证书路径为相对路径时，它的根路径查找顺序为 1）启动参数中conf指定的路径，2）当前的classPath，3）./config/

NOTE: `includes`和`excludes`是排他的，当`includes`不为空时`excludes`将失效

=== WebSocket配置

----
"rpc.websocket": {
  "servicePath": "", <1>
  "host": "127.0.0.1", <2>
  "port": 80 <3>
}
----
<1> WebSocket服务发现的根包，系统会以此包为基础，扫描子孙路径下所有带@RPC及@WebSocket的类，并将其类中带@REQUEST注解的方法加入到路由表中
<2> IP或主机名
<3> 端口号

=== 使用

==== HTTP服务注解及方法定义
[source,scala]
----
 @RPC("/test/") // 指定RPC注解，参数`/test/`表示uri的根路径
 @HTTP // 指定HTTP注解，表示此类可提供HTTP服务
 object DemoService { // 服务可以是object或class

     // 此注解表示此方法对应于HTTP的GET请求
     // 参数为空表示请求的路径是就是根据路径，可接收的请求为 GET /test/
     // 如果参数是 @GET("a/b/c/") 则可接收的请求为 GET /test/a/b/c/
     // 如果要重写根据路径参数以'/'开始即可，如 @GET("/a/b/c/") 则可接收的请求为 GET /a/b/c/
     // 如果参数中带有变量使用':'指定，如 @GET("a/:b/:c/") 则可接收的请求为 GET /test/a/111/222/，方法参数parameter会映射b与c的值
     @GET("")
     // 对于 @GET 和 @DELETE 请求而言，方法的行参有两个
     //    第一个类型是Map[String,String]，用于保存URL中的变量及search值，如 @GET(":id/")，请求为 GET /test/111/?token=sss，则此参数的值为 Map("id" -> "111","token" -> "sss")
     //    第二个类型是EZRPCContext及其子类，保存了请求上下文
     //       请求上下文的参数有：
     //           请求方法 method
     //           请求对应的模块URI（可能带通配符） templateUri
     //           请求的真实URI  realUri
     //           请求URL中的参数  parameters
     //           远程IP remoteIP
     //           请求的Accept accept
     //           请求的ContentType  contentType
     // 返回值必须为Resp封装的类型
     //    Resp中有code，message及body三个属性：
     //      code是返回的业务状态码，与HTTP类似，200表示成功
     //      message是错误的消息描述
     //      body是成功返回的真实对象，在context-Type 是 `*/json`时会将对象转成Json字符串格式返回
     // 几个特殊返回类型：
     //    Resp[File] 返回下载文件流
     //    Resp[RespRedirect] 页面重定向
     //    Resp[Raw] 返回未封装的原始对象
     //    Resp[Document] 当context-Type 是 `text/xml` 时用于返回xml信息（去除Resp封装），xml可由Jsoup处理
     def getTest(parameter: Map[String, String],context: EZRPCContext): Resp[String] = {
       //Resp有多个方法，success表示成功，还有诸如notFound、badRequest、unAuthorized等预定义的错误
       Resp.success("Hello World")
     }

     // 此注解表示此方法对应于HTTP的POST请求
    @POST("")
    // 对于 @POST 和 @PUT 请求而言，方法的行参有三个
    //    第一个和第三个同 @GET 或 @DELETE 请求
    //    第二是任意类型*，系统会将请求body解析成对应的对象
    def getTest(parameter: Map[String, String],body:String, context: EZRPCContext): Resp[String] = {
      Resp.success(String)
    }

 }
----

TIP: 目前POST及PUT请求体不支持直接解析自定义泛型对象，内置类型泛型如Map[String,String]没有问题，但如List[EZ_Resource]这些自定义类型做为泛型时请先使用string（body:String）接收，然后使用JsonHelper.toObject[List[EZ_Resource]](body)转换

IMPORTANT: URI必须严格对应，如 `/test` 与 `/test/` 不是同一个路径

IMPORTANT: URI变量以 `:` 开头，变量名只能是字母或数字


==== WebSocket服务注解及方法定义
[source,scala]
----
 @RPC("/test/") // 指定RPC注解，参数`/test/`表示uri的根路径
 @WebSocket // 指定WebSocket注解，表示此类可提供WebSocket服务
 object DemoService { 

     // 此注解表示此方法支持WebSocket请求，方法形参与HTTP的@POST类似
     @REQUEST("")
     def getTest(parameter: Map[String, String],body:String,context: EZRPCContext): Resp[String] = {
       Resp.success("Hello World")
     }

 }
----

==== SimpleHttpService脚手架

为简化常规的CRUD应用，可继承SimpleHttpService，此类中已定义了基本的CRUD、上传、下载、导出等操作

[source,scala]
----
@RPC("/resource/")
@HTTP
// 继承SimpleHttpService以实现基础服务
// SimpleHttpService第一个泛型指定操作的实体类型，第二个泛型指定上下文类型
object ResourceService extends SimpleHttpService[EZ_Resource, EZRPCContext] {
  // 此属性指定持久化的实现，这里使用EZ_Resource的伴生类
  override protected val storageObj: BaseStorage[EZ_Resource] = EZ_Resource
}

// 这里一个实体，带有两个属性，使用详见`storage`服务
@Entity("Resource")
case class EZ_Resource() extends BaseModel with StatusModel{
  @BeanProperty var method: String = _
  @BeanProperty var uri: String = _
}
// 此伴生类表明此实体可以持久化到Mongo，使用详见`storage`服务
object EZ_Resource extends MongoBaseStorage[EZ_Resource] with MongoStatusStorage[EZ_Resource]
----

上述操作后实现的HTTP服务有：

*添加新资源*

----
POST /resource/ body {"method":"","uri":""}
----

*更新已有资源*

----
PUT /resource/<资源id>/ body {"id":"","method":"","uri":""}
----

*获取一个资源*

----
GET /resource/<资源id>/
----

*删除一个资源*

----
DELETE /resource/<资源id>/
----

*查找资源列表*

----
GET /resource/?condition=<查找条件，sql或mongo json>  condition可选
----

*查找启用资源列表*

----
GET /resource/enable/?condition=<查找条件，sql或mongo json>  condition可选
----

*分页查找资源列表*

----
GET /resource/page/<当前页，从1开始>/<每页显示条数>/?condition=<查找条件，sql或mongo json>  condition可选
----

*启用一个资源*

----
GET /resource/<资源id>/enable/
----

NOTE: 仅在实体继承StatusModel时有效

*禁用一个资源*

----
GET /resource/<资源id>/disable/
----

NOTE: 仅在实体继承StatusModel时有效

*导出资源列表*

----
GET /resource/export/
----

WARNING: 默认会导出所有字段，可能会引发数据安全问题，重写 override protected def allowExportFields = List(<可以导出的字段>) 可以选择导出字段

NOTE: 重写 override protected def allowExport = false 可以禁用导出功能

*上传文件*

----
POST /resource/res/
----

NOTE: 重写 override protected def allowUpload = false 可以禁用上传功能

NOTE: 重写 override protected def allowUploadTypes 可以选择允许上传的类型，如 allowUploadTypes=List(FileType.TYPE_COMPRESS, FileType.TYPE_IMAGE, FileType.TYPE_OFFICE)表示可以上传压缩、图片、Office文档类型

NOTE: 上传文件到：配置文件中的resourcePath + 当前实体的名称 + File.separator + 当前日期(yyyyMMdd) + File.separator

*下载文件*

----
GET <`上传文件`中返回的uri>
----

==== HTTP客户端

===== 同步操作

[source,scala]
.HttpClientProcessor
----
/**
  * GET 请求
  *
  * @param url         请求URL
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def get(url: String, contentType: String = "application/json; charset=utf-8"): String

/**
  * POST 请求
  *
  * @param url         请求URL
  * @param body        请求体
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def post(url: String, body: Any, contentType: String = "application/json; charset=utf-8"): String

/**
  * PUT 请求
  *
  * @param url         请求URL
  * @param body        请求体
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def put(url: String, body: Any, contentType: String = "application/json; charset=utf-8"): String

/**
  * DELETE 请求
  *
  * @param url         请求URL
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def delete(url: String, contentType: String = "application/json; charset=utf-8"): String
----

===== 异步操作

[source,scala]
.HttpClientProcessor.Async
----
/**
  * GET 请求
  *
  * @param url         请求URL
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def get(url: String, contentType: String = "application/json; charset=utf-8"): Future[String]

/**
  * POST 请求
  *
  * @param url         请求URL
  * @param body        请求体
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def post(url: String, body: Any, contentType: String = "application/json; charset=utf-8"): Future[String]

/**
  * PUT 请求
  *
  * @param url         请求URL
  * @param body        请求体
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def put(url: String, body: Any, contentType: String = "application/json; charset=utf-8"): Future[String]

/**
  * DELETE 请求
  *
  * @param url         请求URL
  * @param contentType 请求类型，默认为 application/json; charset=utf-8
  * @return 请求结果，string类型
  */
def delete(url: String, contentType: String = "application/json; charset=utf-8"): Future[String]
----

==== WebSocket消息推送管理

[source,scala]
.WebSocketMessagePushManager
----
/**
  * 向所有客户端推送消息
  *
  * @param method 连接方法，目前只限于 `REQUEST` 方法
  * @param path   连接路径
  * @param data   消息
  */
def ws(method: String, path: String, data: Any): Unit
----
