== Kafka服务

=== 功能

. 实现Kafka服务封装

=== 5分钟上手

. 添加依赖

 <dependency>
   <groupId>com.ecfront</groupId>
   <artifactId>ezf-kafka</artifactId>
   <version>3.2.0</version>
 <dependency>

. 添加配置

 "kafka": {
   "brokerList": "<broker ip:port>"
 }

. 测试服务

 EZManager.start()
 // 定义第一个消费者，属于group1
 val consumer1 = KafkaProcessor.Consumer("group1", "topic1")
 consumer1.receive(new ReceivedCallback {
   override def callback(message: String): Resp[Void] = {
     // 收到消息
     println("consumer1 -> " + message)
     // 关闭此消费者，这时第二个消费者可以收到消息
     consumer1.close()
     Resp.success(null)
   }
 })
 // 定义第二个消费者，也属于group1，第一个与第二消费者是竞争关系，同一消息只会被其中一个消 费
 KafkaProcessor.Consumer("group1", "topic1").receive(new ReceivedCallback {
   override def callback(message: String): Resp[Void] = {
     // 收到消息
     println("consumer2 -> " + message)
     Resp.success(null)
   }
 })
 // 定义第三个消费者，属于group2，这个消费者可以收到所有消息
 KafkaProcessor.Consumer("group2", "topic1").receive(new ReceivedCallback {
   override def callback(message: String): Resp[Void] = {
     // 收到消息
     println("consumer3 -> " + message)
     Resp.success(null)
   }
 })
 // 定义一个生产者
 val producer = KafkaProcessor.Producer("topic1", "client1")
 for (i <- 0 to 5) {
   producer.send(s"【$i】haha...")
 }

=== 依赖

环境依赖：kafka 0.9.x

=== 配置

----
"kafka": {
  "brokerList": "" <1>
}
----
<1> Kafka broker地址列表，格式为: ip:port,...

=== 使用

见示例`com.ecfront.ez.framework.examples.kafka`

=== API

[source,scala]
.KafkaProcessor
----
  /**
  * 生产者类
  *
  * @param topic    主题
  * @param clientId 客户端ID
  */
case class Producer(topic: String, clientId: String) {

    /**
      * 发送消息
      *
      * @param message   消息
      * @param messageId 消息ID，默认自动生成UUID
      */
    def send(message: String, messageId: String = EZContext.createUUID()): Unit

    /**
      * 发送消息
      *
      * @param message   消息
      * @param messageId 消息ID，默认自动生成UUID
      * @return 是否成功 ,返回对应的消息ID（自动生成）和message
      */
    def sendFuture(message: String, messageId: String = EZContext.createUUID()): Future[Resp[(String, String)]]

    /**
      * 发送需要回复的消息
      *
      * @param message  消息
      * @param ackTopic 回复主题
      * @param timeout  等待超时时间（ms）
      * @return 回复的消息
      */
    def ack(message: String, ackTopic: String, timeout: Long = 30 * 1000): Resp[String]

	/**
    * 关闭当前生产者
    */
    def close(): Unit

}

/**
  * 消费者类
  *
  * @param topic              主题
  * @param groupId            组ID，用于发布-订阅模式
  * @param autoCommit         是否自动提交
  * @param autoCommitInterval 自动提供间隔
  */
case class Consumer(topic: String,groupId: String, autoCommit: Boolean = false, autoCommitInterval: Long = DEFAULT_AUTO_COMMIT_INTERVAL) {

    /**
      * 接收消息
      *
      * @param fun      收到消息后的回调方法
      * @param ackTopic 回复主题，如果存在会回复消息
      */
    def receive(fun: (String, String) => Resp[String], ackTopic: String = null): Unit

    /**
      * 关闭当前消费者
      */
    def close(): Unit

}

/**
* 关闭所有实例
*/
def close(): Unit
----
