== 常用分布式服务

=== 功能

. 分布式计数
. 分布式锁
. 分布式Map
. 分布式阻塞和非阻塞队列
. 分布式消息发布订阅
. 分布式追踪日志

=== 5分钟上手

. 添加依赖

 <dependency>
   <groupId>com.ecfront</groupId>
   <artifactId>ezf-distributed</artifactId>
   <version>3.0.0</version>
 <dependency>

. 添加配置

 "distributed": {},
 "redis": {}

. 测试服务

 EZManager.start()
 // 创建test_counter计数器
 val counter = DCounterService("test_counter")
 // 设置成10
 counter.set(10)
 // 加1
 counter.inc()
 // 减1
 counter.dec()
 // 删除
 counter.delete()

=== 依赖

服务依赖：redis

=== 配置

----
"distributed": {}
----

_分布式服务本身没有配置项_

=== 使用

==== 分布式AtomicLong

[source,scala]
.DAtomicLongService(key: String) <1>
----
  def set(value: Long)
  def get: Long
----
<1> key AtomicLong名

==== 分布式阻塞队列

[source,scala]
.DBlockingQueueService[M](key: String) <1>
----
  def put(value: M)
  def peek(): M
  def take(): M
  def size(): Int
  def delete()
----
<1> key 队列名,M 队列项的类型

==== 分布式CountDownLatch

[source,scala]
.DCountDownLatchService(key: String) <1>
----
  def set(value: Long)
  def await(time: Long = -1, unit: TimeUnit = null)
  def get: Long
  def countDown()
  def delete()
----
<1> key CountDownLatch名

==== 分布式原子计数器

[source,scala]
.DCounterService(key: String) <1>
----
  def set(value: Long)
  def get: Long
  def inc(): Long
  def dec(): Long

  /**
    * 有上限的inc
    *
    * @param maxValue 最大值
    * @return 当前值
    */
  def inc(maxValue: Long): Long

  /**
    * 有上限的inc并返回是否增加了
    *
    * @param maxValue 最大值
    * @return 是否增加了，已达上限返回false
    */
  def incWithStatus(maxValue: Long): Boolean

  /**
    * 有下限的dec
    *
    * @param minValue 最小值
    * @return 当前值
    */
  def dec(minValue: Long): Long

  /**
    * 有下限的inc并返回是否减少了
    *
    * @param minValue 最小值
    * @return 是否减少了，已达下限返回false
    */
  def decWithStatus(minValue: Long): Boolean

  def delete()
----
<1> key 计数器名

==== 分布式锁

[source,scala]
.DLockService(key: String) <1>
----
  def lock(leaseTime: Long = -1, unit: TimeUnit = null)
  def tryLock(waitTime: Long = 0, leaseTime: Long = -1, unit: TimeUnit = TimeUnit.MILLISECONDS): Boolean
  def unLock(): Boolean
  def isLock: Boolean
  def delete()
----
<1> key 锁名

==== 分布式Map，key为string , value为自定义类型

[source,scala]
.DMapService[M](key: String) <1>
----
  def put(key: String, value: M)
  def putIfAbsent(key: String, value: M)
  def contains(key: String): Boolean
  def foreach(fun: (String, M) => Unit)
  def get(key: String): M
  def remove(key: String)
  def clear()
----
<1> key Map名,M Map项的类型

==== 分布式队列（不阻塞）

[source,scala]
.DQueueService[M](key: String) <1>
----
  def add(value: M)
  def peek(): M
  def poll(): M
  def size(): Int
  def delete()
----
<1> key 队列名,M 队列项的类型

==== 分布式消息队列

[source,scala]
.DMQService[M](key: String) <1>
----
  def publish(message: M) // 发布消息
  def subscribe(fun: => M => Unit) // 订阅消息
  def subscribeOneNode(fun: => M => Unit) // 订阅消息，一条消息只由一个节点处理
  def send(message: M) // 发送消息(point to point)
  def receive(fun: => M => Unit) // 接收消息(point to point)
----
<1> key 消息队列名,M 消息队列项的类型

==== 分布式服务监控

此功能用监控服务状态,在需要被监控的服务中调用`DMonitorService.start()`即可开启监控

NOTE: 心跳默认时间间隔是`60秒`

服务状态管理:

[source,scala]
.DMonitorService.Manager
----
/**
  * 获取所有服务
  *
  * @return 所有服务
  */
def fetchAllServices: Map[String, DService]

/**
  * 删除一个服务
  *
  * @param key 要删除的服务key
  */
def removeAService(key: String): Unit

/**
  * 删除所有服务
  */
def removeAllServices(): Unit

/**
  * 获取服务状态报告
  *
  * @return 服务状态报告
  */
def fetchLiveReport: Map[String, Long]
----

==== 分布式追踪日志

[source,scala]
.DTrace
----
/**
    * 追踪日志流程定义
    *
    * @param flowCode 流程code,要求全局唯一
    * @param flow     流程定义，支持分支，如
    *                 List(
    *                 "m1#s1",
    *                 "m1#s2",
    *                 List(
    *                 List("m2#s3-1", "m2#s4-1"),
    *                 List("m3#s3-2")
    *                 ),
    *                 "m1#s5"
    *                 )
    */
def define(flowCode: String, flow: List[Any]): Unit

/**
    * 写日志
    *
    * @param clueId   追踪线索，每个流程实例唯一，如贷款流程追踪可用身份证号做为clueId
    * @param flowCode 日志流程定义code
    * @param module   当前模块
    * @param stage    当前阶段
    * @param message  消息
    */
def log(clueId: String, flowCode: String, module: String, stage: String, message: String): Unit

/**
  * 写日志
  *
  * @param clueId   追踪线索，每个流程实例唯一，如贷款流程追踪可用身份证号做为clueId
  * @param flowCode 日志流程定义code
  * @param module   当前模块
  * @param stage    当前阶段
  * @param message  消息
  */
def flowLog(flowCode: String)(clueId: String, module: String, stage: String, message: String): Unit = {

/**
  * 写日志
  *
  * @param clueId   追踪线索，每个流程实例唯一，如贷款流程追踪可用身份证号做为clueId
  * @param flowCode 日志流程定义code
  * @param nodeCode 当前节点code，由模块#阶段 组成
  * @param message  消息
  */
def simpleLog(flowCode: String)(clueId: String, nodeCode: String, message: String): Unit
----

[source,scala]
.例子
----
// 定义一套流程，带分支
DTrace.define("testFlow", List(
  "m1#s1",
  "m1#s2",
  List(
    List("m2#s3-1", "m2#s4-1"),
    List("m3#s3-2")
  ),
  "m1#s5"
))

// 写日志，流程实例1，走第一个分支
DTrace.log("jzy1","testFlow","m1","s1","step1")
DTrace.log("jzy1","testFlow","m1","s2","step2")
DTrace.log("jzy1","testFlow","m2","s3-1","step3")
DTrace.log("jzy1","testFlow","m2","s4-1","step4")
DTrace.log("jzy1","testFlow","m1","s5","step5")

// 写日志，流程实例2，走第二个分支
DTrace.log("jzy2","testFlow","m1","s1","step1")
DTrace.log("jzy2","testFlow","m1","s2","step2")
DTrace.log("jzy2","testFlow","m3","s3-2","step3")
DTrace.log("jzy2","testFlow","m1","s5","step4")

// 写日志，流程实例3，有未经过的节点
DTrace.log("jzy3","testFlow","m1","s1","step1")
DTrace.log("jzy3","testFlow","m3","s3-2","step3")
DTrace.log("jzy3","testFlow","m1","s5","step4")

// 写日志，流程实例4，有未经过的节点
DTrace.log("jzy4","testFlow","m1","s1","step1")
DTrace.log("jzy4","testFlow","m1","s2","step2")
DTrace.log("jzy4","testFlow","m2","s3-1","step3")
DTrace.log("jzy4","testFlow","m1","s5","step5")

// 输出结果（类似）

======================== START [testFlow] ========================
===== Trace [testFlow] for [jzy1] at [m1]-[s1] : step1
===== Flow []
--------------------------------------------------------------------
09:57:50.497 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy1] at [m1]-[s2] : step2
===== Flow [m1#s1 > ]
--------------------------------------------------------------------
09:57:50.511 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy1] at [m2]-[s3-1] : step3
===== Flow [m1#s1 > m1#s2 > ]
--------------------------------------------------------------------
09:57:50.523 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy1] at [m2]-[s4-1] : step4
===== Flow [m1#s1 > m1#s2 > m2#s3-1 > ]
--------------------------------------------------------------------
09:57:50.530 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy1] at [m1]-[s5] : step5
===== Flow [m1#s1 > m1#s2 > m2#s3-1 > m2#s4-1 > ]
===== Result [SUCCESS] , Use Time [366ms]
======================== FINISH [testFlow] ========================
09:57:50.534 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
======================== START [testFlow] ========================
===== Trace [testFlow] for [jzy2] at [m1]-[s1] : step1
===== Flow []
--------------------------------------------------------------------
09:57:50.559 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy2] at [m1]-[s2] : step2
===== Flow [m1#s1 > ]
--------------------------------------------------------------------
09:57:50.573 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy2] at [m3]-[s3-2] : step3
===== Flow [m1#s1 > m1#s2 > ]
--------------------------------------------------------------------
09:57:50.587 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy2] at [m1]-[s5] : step4
===== Flow [m1#s1 > m1#s2 > m3#s3-2 > ]
===== Result [SUCCESS] , Use Time [54ms]
======================== FINISH [testFlow] ========================
09:57:50.589 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
======================== START [testFlow] ========================
===== Trace [testFlow] for [jzy3] at [m1]-[s1] : step1
===== Flow []
--------------------------------------------------------------------
09:57:50.603 [ScalaTest-run-running-TraceSpec] WARN  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy3] at [m3]-[s3-2] : step3
===== Flow [m1#s1 > ]
===== Expect current in [m1#s2] But real current is m3#s3-2
--------------------------------------------------------------------
09:57:50.611 [ScalaTest-run-running-TraceSpec] WARN  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy3] at [m1]-[s5] : step4
===== Flow [m1#s1 > m3#s3-2 > ]
===== Result [FAIL] , Use Time [22ms]
======================== FINISH [testFlow] ========================
09:57:50.615 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
======================== START [testFlow] ========================
===== Trace [testFlow] for [jzy4] at [m1]-[s1] : step1
===== Flow []
--------------------------------------------------------------------
09:57:50.629 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy4] at [m1]-[s2] : step2
===== Flow [m1#s1 > ]
--------------------------------------------------------------------
09:57:50.645 [ScalaTest-run-running-TraceSpec] INFO  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy4] at [m2]-[s3-1] : step3
===== Flow [m1#s1 > m1#s2 > ]
--------------------------------------------------------------------
09:57:50.657 [ScalaTest-run-running-TraceSpec] WARN  c.e.e.f.s.distributed.trace.DTrace$ -
--------------------------------------------------------------------
===== Trace [testFlow] for [jzy4] at [m1]-[s5] : step5
===== Flow [m1#s1 > m1#s2 > m2#s3-1 > ]
===== Expect current in [m2#s4-1] But real current is m1#s5
===== Result [FAIL] , Use Time [42ms]
======================== FINISH [testFlow] ========================
----
